# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1e3183c41ff89c6a7b35fffc81db09af5d4be11435b1a6bc5999a19f6772857a3ead160ba82e3b78366f0f364fa81aa22072fcdeca34868cfdc90e702b1b406b

test:
  secret_key_base: 8c0ce92cc551e1a5025462cd39f98f29bf6a736370ce88897695997ace25b961f1a6727492edbe06e3b156988e0ad006cbfb2d5480654d7547d3a3fd29789092

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
